version: '3.8'

services:
  angular:
    build:
      context: ./ng-rails
      dockerfile: Dockerfile # Adjust the path to your Angular Dockerfile
    networks:
      - app-network

  rails:
    build:
      context: ./ror-sample
      dockerfile: Dockerfile # Adjust the path to your Rails Dockerfile
    networks:
      - app-network

  nginx-reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile # Adjust the path to your NGINX Dockerfile
    depends_on:
      - angular
      - rails
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
